# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoEarlGrey3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for demoEarlGrey3

  target 'demoEarlGrey3Tests' do
    inherit! :search_paths
	pod 'EarlGrey'
    # Pods for testing
  end

end
